#!/usr/bin/env python3
"""Construct a valid, symmetric crossword GRID with locked theme answers.

This is the hard, deterministic part of making a crossword: producing a grid
where every Across and Down entry is a real, reasonably-common word, with
180-degree rotational symmetry and your theme answers placed where you want
them. Clue-writing is a separate, human/Claude step (see SKILL.md).

How it works (the recipe we converged on after a lot of iteration):
  - Words come from a *scored* crossword wordlist (assets/wordlist.dict,
    "WORD;score"). Higher score = cleaner entry. We only pool entries at or
    above --min-score, so even forced fill stays fair.
  - Theme answers are placed as Across entries in symmetric rows and locked.
  - A symmetric block skeleton is generated by splitting over-long runs.
  - The grid is filled by backtracking with: most-constrained-slot first,
    1-step feasibility filtering (drop dead-ends), and common-words-first
    ordering. A *short* per-fill timeout means we abandon hard skeletons fast
    and keep the ones that fill quickly.
  - We generate many grids and keep the cleanest (fewest low-score entries).

Usage:
  python build_grid.py --theme "ELIZABETHBENNET,GEORGEKNIGHTLEY" \
      --size 15 --out /path/to/outdir

Output: <out>/solution.json  ({size, black, grid})  and a printed entry list.
Run assemble.py next to attach clues and emit the final puzzle JSON + player.
"""
import argparse, json, os, random, re, sys, time
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_WORDLIST = os.path.join(HERE, "..", "assets", "wordlist.dict")

# crosswordese / junk to keep out regardless of score
PROFANITY = set("""damn hell ass asshole bastard bitch shit fuck fucked fucking
piss cock dick pussy slut whore cunt bollocks wanker prick twat goddamn""".split())

# ----------------------------------------------------------------- word pool
def load_pool(path, N, min_score, theme_words):
    score = {}
    with open(path) as f:
        for line in f:
            if ";" not in line: continue
            w, s = line.rstrip("\n").rsplit(";", 1)
            w = w.lower()
            if not re.fullmatch(r"[a-z]+", w): continue
            if not (3 <= len(w) <= N): continue
            if w in PROFANITY: continue
            try: sc = int(s)
            except ValueError: continue
            if sc < min_score: continue
            if sc > score.get(w, -1): score[w] = sc
    for w in theme_words:
        score[w.lower()] = 100
    rank = {w: 100 - sc for w, sc in score.items()}  # lower rank = higher score
    by_len = defaultdict(list)
    for w in score: by_len[len(w)].append(w)
    for L in by_len: by_len[L].sort(key=lambda w: rank[w])
    idx = {}
    for L, lst in by_len.items():
        d = defaultdict(set)
        for i, w in enumerate(lst):
            for p, ch in enumerate(w): d[(p, ch)].add(i)
        idx[L] = d
    all_idx = {L: set(range(len(lst))) for L, lst in by_len.items()}
    return score, rank, by_len, idx, all_idx

# ----------------------------------------------------------------- theme place
def place_theme(N, words):
    """Place theme answers as Across entries in symmetric rows.

    Returns (theme_rows, locked_black, locked_white) where theme_rows maps
    row -> (word, start_col). Works for grid-spanning answers (length == N) and
    for equal-length mirror pairs; a single odd-one-out goes in the center row
    when the parity allows clean self-symmetry. Raises ValueError with guidance
    otherwise so the caller can pick better theme answers.
    """
    from collections import Counter
    words = [w for w in words if w]
    for w in words:
        if not (3 <= len(w) <= N):
            raise ValueError(f"theme answer {w!r} must be 3..{N} letters for a {N}-grid")
    # group equal lengths into pairs; allow one leftover
    bylen = defaultdict(list)
    for w in words: bylen[len(w)].append(w)
    pairs, singles = [], []
    for L, ws in bylen.items():
        while len(ws) >= 2: pairs.append((ws.pop(), ws.pop()))
        if ws: singles.append(ws.pop())
    if len(singles) > 1:
        raise ValueError(
            "theme answers should form equal-length mirror pairs (plus at most "
            f"one center answer). Got unpaired lengths {[len(s) for s in singles]}. "
            "Pick answers so they pair up by length (e.g. two 15s, or two 13s + one center).")
    # symmetric row slots, outermost first (keeps theme rows clear of the edges
    # and reasonably spread); pairs consume (r, N-1-r)
    offsets = []
    o = max(2, N // 5)
    while o < N // 2:
        offsets.append(o); o += 2
    if len(pairs) > len(offsets):
        raise ValueError(f"too many theme pairs ({len(pairs)}) for a {N}-grid")
    theme_rows = {}
    locked_black, locked_white = set(), set()
    def lay(row, word):
        L = len(word); p = (N - L) // 2
        theme_rows[row] = (word, p)
        for c in range(N):
            if p <= c < p + L: locked_white.add((row, c))
            else: locked_black.add((row, c))
        return p
    for k, (wa, wb) in enumerate(pairs):
        rt = offsets[k]; rb = N - 1 - rt
        L = len(wa)
        p = (N - L) // 2
        # top at p, bottom at mirrored column N-L-p  -> guarantees grid symmetry
        theme_rows[rt] = (wa, p)
        theme_rows[rb] = (wb, N - L - p)
        for c in range(N):
            (locked_white if p <= c < p + L else locked_black).add((rt, c))
        pb = N - L - p
        for c in range(N):
            (locked_white if pb <= c < pb + L else locked_black).add((rb, c))
    if singles:
        w = singles[0]; L = len(w)
        if (N - L) % 2 != 0:
            raise ValueError(
                f"the unpaired theme answer {w!r} (len {L}) can't sit symmetrically "
                f"in a {N}-grid's center row. Give it a same-length partner, or pick "
                f"one whose length has the same parity as {N}.")
        if N % 2 == 0:
            raise ValueError("a single center theme answer needs an odd grid size")
        lay(N // 2, w)
    return theme_rows, locked_black, locked_white

# ----------------------------------------------------------------- skeleton
def make_skeleton_tools(N, MAXLEN, theme_rows, locked_black, locked_white):
    theme_set = set(theme_rows)

    def runs_ok(black):
        too_long = too_short = 0
        for r in range(N):
            if r in theme_set: continue
            c = 0
            while c < N:
                if black[r][c]: c += 1; continue
                s = c
                while c < N and not black[r][c]: c += 1
                L = c - s
                if L < 3: too_short += 1
                elif L > MAXLEN: too_long += 1
        for c in range(N):
            r = 0
            while r < N:
                if black[r][c]: r += 1; continue
                s = r
                while r < N and not black[r][c]: r += 1
                L = r - s
                if L < 3: too_short += 1
                elif L > MAXLEN: too_long += 1
        return too_long, too_short

    def long_runs(black):
        out = []
        for r in range(N):
            if r in theme_set: continue
            c = 0
            while c < N:
                if black[r][c]: c += 1; continue
                s = c
                while c < N and not black[r][c]: c += 1
                if c - s > MAXLEN: out.append([(r, cc) for cc in range(s, c)])
        for c in range(N):
            r = 0
            while r < N:
                if black[r][c]: r += 1; continue
                s = r
                while r < N and not black[r][c]: r += 1
                if r - s > MAXLEN: out.append([(rr, c) for rr in range(s, r)])
        return out

    def connected(black):
        cells = [(r, c) for r in range(N) for c in range(N) if not black[r][c]]
        if not cells: return False
        seen = {cells[0]}; st = [cells[0]]
        while st:
            r, c = st.pop()
            for dr, dc in ((1,0),(-1,0),(0,1),(0,-1)):
                nr, nc = r+dr, c+dc
                if 0<=nr<N and 0<=nc<N and not black[nr][nc] and (nr,nc) not in seen:
                    seen.add((nr,nc)); st.append((nr,nc))
        return len(seen) == len(cells)

    def base_black():
        b = [[False]*N for _ in range(N)]
        for (r, c) in locked_black: b[r][c] = True
        return b

    def gen():
        for _ in range(4000):
            black = base_black()
            stuck = False
            for _ in range(500):
                lr = long_runs(black)
                if not lr: break
                run = max(lr, key=len); Lr = len(run)
                ks = list(range(3, Lr - 3)); random.shuffle(ks)
                done = False
                for k in ks:
                    r, c = run[k]; r2, c2 = N-1-r, N-1-c
                    if r in theme_set or r2 in theme_set: continue
                    if (r, c) in locked_white or (r2, c2) in locked_white: continue
                    if black[r][c] or black[r2][c2]: continue
                    black[r][c] = black[r2][c2] = True
                    if runs_ok(black)[1] > 0:           # made a 1/2-letter run
                        black[r][c] = black[r2][c2] = False; continue
                    done = True; break
                if not done: stuck = True; break
            if stuck: continue
            tl, ts = runs_ok(black)
            if tl == 0 and ts == 0 and connected(black):
                bc = sum(black[r][c] for r in range(N) for c in range(N))
                yield black, bc

    return gen

# ----------------------------------------------------------------- fill
class Slot:
    __slots__ = ("id","cells","L","cands","filled","cross")
    def __init__(self, sid, cells):
        self.id=sid; self.cells=cells; self.L=len(cells)
        self.cands=None; self.filled=False; self.cross=[]

def extract_slots(black, N):
    slots=[]; cell_slots=defaultdict(list)
    def add(cells):
        sl=Slot(len(slots),cells); slots.append(sl)
        for cell in cells: cell_slots[cell].append(sl)
    for r in range(N):
        c=0
        while c<N:
            if black[r][c]: c+=1; continue
            s=c
            while c<N and not black[r][c]: c+=1
            if c-s>=2: add([(r,cc) for cc in range(s,c)])
    for c in range(N):
        r=0
        while r<N:
            if black[r][c]: r+=1; continue
            s=r
            while r<N and not black[r][c]: r+=1
            if r-s>=2: add([(rr,c) for rr in range(s,r)])
    for sl in slots:
        for ps,cell in enumerate(sl.cells):
            for t in cell_slots[cell]:
                if t.id!=sl.id: sl.cross.append((t, ps, t.cells.index(cell)))
    return slots, cell_slots

EMPTY=frozenset()

def candidates(letters, L, idx, all_idx):
    cons=[(p,ch) for p,ch in enumerate(letters) if ch is not None]
    if not cons: return all_idx[L]
    cons.sort(key=lambda pc: len(idx[L].get(pc,())))
    base=idx[L].get(cons[0])
    if not base: return set()
    res=set(base)
    for pc in cons[1:]:
        res &= idx[L].get(pc, set())
        if not res: break
    return res

def fill(black, N, theme_rows, by_len, idx, all_idx, time_budget):
    slots, cell_slots = extract_slots(black, N)
    grid=[[None]*N for _ in range(N)]
    used=set()
    for r,(word,start) in theme_rows.items():
        w=word.lower()
        for i,ch in enumerate(w): grid[r][start+i]=ch
        used.add(w)
    for sl in slots:
        lt=[grid[r][c] for (r,c) in sl.cells]
        if all(x is not None for x in lt): sl.filled=True; used.add("".join(lt))
        else: sl.cands=candidates(lt, sl.L, idx, all_idx)
    start=time.time()

    def recurse():
        if time.time()-start>time_budget: raise TimeoutError
        best=None; best_cnt=1<<30
        for sl in slots:
            if sl.filled: continue
            c=len(sl.cands)
            if c==0: return False
            if c<best_cnt: best_cnt=c; best=sl
        if best is None: return True
        sl=best; L=sl.L
        cross=[(t,ps,pt) for (t,ps,pt) in sl.cross if not t.filled]
        cand=sorted(sl.cands); feas=[]; tail=[]; checked=0
        for i in cand:
            w=by_len[L][i]
            if w in used: continue
            if checked<70:
                checked+=1; ok=True
                for (t,ps,pt) in cross:
                    sub=idx[t.L].get((pt,w[ps]))
                    if sub is None or not (t.cands & sub): ok=False; break
                if ok: feas.append(w)
            else: tail.append(w)
        head=feas[:8]; random.shuffle(head); order=head+feas[8:]+tail
        for w in order:
            old=[grid[r][c] for (r,c) in sl.cells]
            for (r,c),ch in zip(sl.cells,w): grid[r][c]=ch
            sl.filled=True; used.add(w); touched=[]; ok=True
            for (t,ps,pt) in cross:
                touched.append((t,t.cands))
                t.cands=t.cands & idx[t.L].get((pt,w[ps]),EMPTY)
                if not t.cands: ok=False; break
            if ok and recurse(): return True
            for (t,prev) in touched: t.cands=prev
            sl.filled=False; used.discard(w)
            for (r,c),ch in zip(sl.cells,old): grid[r][c]=ch
        return False
    try:
        if recurse(): return grid
    except TimeoutError:
        return None
    return None

# ----------------------------------------------------------------- entries / quality
def get_entries(black, grid, N):
    num=[[0]*N for _ in range(N)]; n=0; starts=[]
    for r in range(N):
        for c in range(N):
            if black[r][c]: continue
            a=(c==0 or black[r][c-1]) and c+1<N and not black[r][c+1]
            d=(r==0 or black[r-1][c]) and r+1<N and not black[r+1][c]
            if a or d: n+=1; num[r][c]=n; starts.append((r,c,a,d))
    entries=[]
    for (r,c,a,d) in starts:
        if a:
            cc=c; cells=[]
            while cc<N and not black[r][cc]: cells.append((r,cc)); cc+=1
            entries.append({"num":num[r][c],"dir":"across","row":r,"col":c,
                            "len":len(cells),"answer":"".join(grid[y][x] for y,x in cells)})
        if d:
            rr=r; cells=[]
            while rr<N and not black[rr][c]: cells.append((rr,c)); rr+=1
            entries.append({"num":num[r][c],"dir":"down","row":r,"col":c,
                            "len":len(cells),"answer":"".join(grid[y][x] for y,x in cells)})
    return entries, num

def validate(black, grid, N, words_set, theme_rows):
    issues=[]
    for r in range(N):
        for c in range(N):
            if black[r][c]!=black[N-1-r][N-1-c]: issues.append("asymmetry")
    entries,_=get_entries(black, grid, N); seen=set()
    for e in entries:
        w=e["answer"]
        if e["len"]<3: issues.append(f"short:{w}")
        if w not in words_set: issues.append(f"notword:{w}")
        if w in seen: issues.append(f"dup:{w}")
        seen.add(w)
    for r,(word,start) in theme_rows.items():
        got="".join(grid[r][start+i] for i in range(len(word)))
        if got!=word.lower(): issues.append(f"theme row {r}: {got} != {word}")
    return issues, entries

def quality(entries, score):
    weak=0; worst=100; deficit=0
    for e in entries:
        sc=score.get(e["answer"],0); deficit+=100-sc
        if sc<60: weak+=1
        worst=min(worst, sc)
    return (weak, -worst, deficit)

# ----------------------------------------------------------------- driver
def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--theme", required=True, help="comma-separated theme answers")
    ap.add_argument("--size", type=int, default=15)
    ap.add_argument("--out", required=True, help="output directory")
    ap.add_argument("--wordlist", default=DEFAULT_WORDLIST)
    ap.add_argument("--min-score", type=int, default=60)
    ap.add_argument("--search-seconds", type=float, default=90.0)
    ap.add_argument("--time-budget", type=float, default=0.8)
    ap.add_argument("--maxlen", type=int, default=7)
    ap.add_argument("--seed", type=int, default=20260627)
    args=ap.parse_args()
    random.seed(args.seed)
    N=args.size
    theme_words=[re.sub(r"[^A-Za-z]","",w).upper() for w in args.theme.split(",")]
    theme_words=[w for w in theme_words if w]
    if not theme_words: sys.exit("no usable theme answers")

    try:
        theme_rows, lblack, lwhite = place_theme(N, theme_words)
    except ValueError as e:
        sys.exit(f"THEME PLACEMENT ERROR: {e}")

    score, rank, by_len, idx, all_idx = load_pool(args.wordlist, N, args.min_score, theme_words)
    words_set=set(score)
    # theme answers must exist as fill-legal words (they were force-added at score 100)
    print(f"pool: {len(words_set)} words (min_score={args.min_score}); "
          f"theme rows: { {r: w for r,(w,_) in theme_rows.items()} }", flush=True)

    gen = make_skeleton_tools(N, args.maxlen, theme_rows, lblack, lwhite)
    t0=time.time(); best=None; solved=0; attempts=0
    skeletons=gen()
    for black, bc in skeletons:
        attempts+=1
        grid=fill(black, N, theme_rows, by_len, idx, all_idx, args.time_budget)
        if grid is not None:
            issues, entries = validate(black, grid, N, words_set, theme_rows)
            if not issues:
                solved+=1; q=quality(entries, score)
                if best is None or q<best[0]:
                    best=(q, black, grid, entries)
                    print(f"  new best: sub60={q[0]} min_score={-q[1]} "
                          f"(valid fills so far: {solved}) at {time.time()-t0:.0f}s", flush=True)
        if time.time()-t0>args.search_seconds and best is not None: break
        if time.time()-t0>args.search_seconds*1.8:
            print("hard wall reached", flush=True); break
    if best is None:
        sys.exit("FAILED to construct a valid grid. Try: fewer/shorter theme answers, "
                 "a lower --min-score (e.g. 55), or a longer --search-seconds.")
    q, black, grid, entries = best
    os.makedirs(args.out, exist_ok=True)
    with open(os.path.join(args.out,"solution.json"),"w") as f:
        json.dump({"size":N,"black":black,"grid":grid}, f)
    print(f"\nSOLVED: {solved} valid grids explored; chose sub60={q[0]} min_score={-q[1]}")
    print("\nGRID:")
    for r in range(N):
        print(" ".join((grid[r][c].upper() if grid[r][c] else "#") for c in range(N)))
    ac=sorted([e for e in entries if e["dir"]=="across"], key=lambda e:e["num"])
    dn=sorted([e for e in entries if e["dir"]=="down"], key=lambda e:e["num"])
    print("\nENTRIES (write a clue for each in clues.json):")
    print("ACROSS: "+", ".join(f'{e["num"]}={e["answer"].upper()}' for e in ac))
    print("DOWN:   "+", ".join(f'{e["num"]}={e["answer"].upper()}' for e in dn))
    low=sorted(entries, key=lambda e:score.get(e["answer"],0))[:10]
    print("\nlowest-scored entries (eyeball these): " +
          ", ".join(f'{e["answer"].upper()}({score.get(e["answer"],0)})' for e in low))

if __name__=="__main__":
    main()
